### PR TITLE
Port to 1.20.1

### PR DESCRIPTION
**Pull request by ghost**
Behold, for ‘tis public.  Once moe, I hast gained permission to port thy mod

### CODE REVIEW

**Comment by ghost** [comment]
Whoops the port was for fabric, will switch to quilt before submitting for review

**Comment by cph101** [comment]
No crashes yet, all mobs work as expected. Have not tested:
- Mason death explosion
- Merchant simulacrum
- Soulmould eyes layer

**Comment by ghost** [comment]
Also added Impaled compat, now hellforks and soulforks can be swapped using the soullights and torchlights, identical to the behaviour when used on vanilla torch/lantern variants

Edit: please wait before merging, I want to add Effective compat first

**Comment by ghost** [comment]
Just showing Impaled compat here:


Effective compat is also added now :D

**Pull request closed without merging**
